### ISSUE TITLE
I cannot  implement RenderItem?

### ISSUE THREAD

**Issue by hoichemgio9x** [Heerbann/Box2dCamera#1]
I create file RenderSprite.java and cannot implement RenderItem from file Box2DCamera.java

**Comment by Heerdam** [comment]
my best guess is that you have to implement Box2DCamera.RenderItem instead of just RenderItem

e.g.: `public class Foo implements Box2DCamera.RenderItem {}`

**Comment by hoichemgio9x** [comment]
> my best guess is that you have to implement Box2DCamera.RenderItem instead of just RenderItem
> 
> e.g.: `public class Foo implements Box2DCamera.RenderItem {}`

Okay. Method Gdx.graphics.getFrameId() doesn't existing and var miniCam is Camera can't create new OrthographicCamera. Help me

**Comment by Heerdam** [comment]
this is for issues with the project and not tutorialspoint

**Comment by manuel5975p** [comment]
damn. bitch got served

**Comment by hoichemgio9x** [comment]
> this is for issues with the project and not tutorialspoint

Ok. Fix success. Thank you
